[2025-04-28T09-26-35-943Z] ERROR:
Name: Error
Message: UNHANDLED_REJECTION
Stack:
Error: UNHANDLED_REJECTION
    at Object.error (/home/container/events/logger.js:152:27)
    at process.<anonymous> (/home/container/index.js:210:10)
    at process.emit (node:events:518:28)
    at emitUnhandledRejection (node:internal/process/promises:252:13)
    at throwUnhandledRejectionsMode (node:internal/process/promises:388:19)
    at processPromiseRejections (node:internal/process/promises:475:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:106:32)
Metadata: {
  "requestBody": {
    "files": [],
    "json": {
      "type": 4,
      "data": {
        "content": "Error al procesar la interacci√≥n",
        "tts": false,
        "enforce_nonce": false,
        "flags": 64
      }
    }
  },
  "rawError": {
    "message": "Interaction has already been acknowledged.",
    "code": 40060
  },
  "code": 40060,
  "status": 400,
  "method": "POST",
  "url": "https://discord.com/api/v10/interactions/1366344841323221022/aW50ZXJhY3Rpb246MTM2NjM0NDg0MTMyMzIyMTAyMjpnUXBSMFhGdFc2WDVJbGtDR3JyYXZ5SHYzUmFHbUhNbENETnBCeWVUNTFQR1F1VUR3dDN3RzVhRVAyQlFxTUtRTzBwSHpZdjdTR1RBazBtU3RHbmdhVUdhcmdRN1BjN0hGcDV4TWY2M3lGQlBEVFpqdmx5SUpHbWRraWN5dnNGMA/callback?with_response=false"
}

