[2025-04-28T00-42-48-941Z] ERROR:
Name: Error
Message: UNHANDLED_REJECTION
Stack:
Error: UNHANDLED_REJECTION
    at Object.error (/home/container/events/logger.js:152:27)
    at process.<anonymous> (/home/container/index.js:210:10)
    at process.emit (node:events:518:28)
    at emitUnhandledRejection (node:internal/process/promises:252:13)
    at throwUnhandledRejectionsMode (node:internal/process/promises:388:19)
    at processPromiseRejections (node:internal/process/promises:475:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:106:32)
Metadata: {
  "requestBody": {
    "files": [],
    "json": {
      "type": 4,
      "data": {
        "content": "Error al procesar la interacci√≥n",
        "tts": false,
        "enforce_nonce": false,
        "flags": 64
      }
    }
  },
  "rawError": {
    "message": "Interaction has already been acknowledged.",
    "code": 40060
  },
  "code": 40060,
  "status": 400,
  "method": "POST",
  "url": "https://discord.com/api/v10/interactions/1366213027086602361/aW50ZXJhY3Rpb246MTM2NjIxMzAyNzA4NjYwMjM2MTpuR1RrM0cwblRjd2M0N0V1dEluT3lXdlRHTDFtMW15Q2s1MDVEV2NhS0pCT2Q1V2RabVExaERFQkpKd05QR2lwTlI3VnVDS1hoS0pwTzJXdWNidjJyREpmb1Z6aFd2d0JFd3cyWlo0bEM2S0x5d05PS0NaZWpjVjliT2NGbWlUaw/callback?with_response=false"
}

